ManageIQ/manageiq-providers-kubernetes

config/settings.yml

Moving kubernetes related events from provider-openshift to correct repo.
cc: @cben @simon3z

move kubernetes related events

---

app/models/manageiq/providers/kubernetes/container_manager/entities_mapping.rb
app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb

Adding a static mapping between k8s entities to miq entities.

Add mapping for Container entities

---

config/settings.yml

Issue #2 
Moving kubernetes related settings
cc: @cben @simon3z

move kubernetes related settings

---

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture.rb
app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/capture_context.rb

Containers and ContainerGroups that are not associated with a node yet (e.g. still Pending) are throwing the `Validation error: cores not defined` exception at metrics collection time. This is not correct, metrics should not be collected from pending containers and pods, we should not throw exception in this case.
This PR replace this exception with a warning.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1458797

Warn if no hardware

---

app/models/manageiq/providers/kubernetes/container_manager/entities_mapping.rb
app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb

As discussed in https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/18
@miq-bot add_label refactoring
@simon3z @moolitayer Please review
cc @kevensen

Rename miq_entity method

---

.rubocop_local.yml
app/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin.rb
app/models/manageiq/providers/kubernetes/container_manager/kubernetes_event_monitor.rb

Move kubernetes code from gems pending to relevant repo.
Issue #19 
Miq gems PR:https://github.com/ManageIQ/manageiq-gems-pending/pull/185
cc: @cben @simon3z @chessbyte

Move kubernetes code from gems-pending

---

.rspec
.rspec_ci
bin/setup
bin/update
config/settings.yml
lib/tasks_private/spec.rake
spec/spec_helper.rb

ran the generator again with
```bash
bundle exec rails g provider <name> --path ../
```
these are the changes.

run provider generator to sync changes from core

---

spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb

Split from #60, I'm gonna wait with the change there, but more tests are
always good :-)
@miq-bot add-label test
@zeari @zakiva Please review

Add parse_service spec

---

.rubocop_local.yml
app/models/manageiq/providers/kubernetes/container_manager.rb
app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
app/models/manageiq/providers/kubernetes/monitoring_manager.rb
app/models/manageiq/providers/kubernetes/monitoring_manager_mixin.rb
app/models/manageiq/providers/kubernetes/prometheus/message_buffer_client.rb
config/settings.yml
spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
spec/models/manageiq/providers/kubernetes/monitoring_manager_spec.rb
spec/vcr_cassettes/manageiq/providers/kubernetes/monitoring_manager.yml

This is the second item of ManageIQ/manageiq-providers-kubernetes#39
Depends on: 
- [merged] https://github.com/ManageIQ/manageiq/pull/15354
- [merged] https://github.com/ManageIQ/manageiq/pull/15604
- [merged] https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/68 (fix tests)
- [merged] https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/72 (fix tests)

Add kubernetes monitoring manager

---

app/models/manageiq/providers/kubernetes/container_manager/refresher.rb

Concrete benefit is separate `realtime_block` timing.

Refresher: Split collection from parsing methods

---

app/models/manageiq/providers/kubernetes/container_manager.rb

https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/45#discussion_r131666832

require_nested for Kubernetes::ContainerManager::Options

---

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_mixin.rb
app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_spec.rb
spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_fail_connect.yml
spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_try_connect.yml

Moving https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/102 because Nimrod is on vacation .

Add prometheus authentication and refactored prometheus client

---

app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb

Created helpers for the pattern of looking in `@data_index`, if not there adding to `@data` and `@data_index`.
Repays some of the tech debt from #11.
I also have upcoming use for `find_or_store_data` — to keep track of all mapped tags, allowing some batching (faster and needed for tag mapping in graph refresh).
@miq-bot add-label refactoring

Refactor parse_container_image

---

app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb
spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb

Parse the quotas as numeric (int or float) values instead of string. 
Depends on https://github.com/ManageIQ/manageiq-schema/pull/44
@simon3z @zeari Please review

Convert quotas to numeric values

---

config/settings.yml

Needed for https://github.com/ManageIQ/manageiq/pull/15978

Move log setting to provider

---

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb

Name custom attributes ICs nicely, so it shows up nicely in log and the graph.

Name custom attributes ICs nicely

---

app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb
spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb

bz: https://bugzilla.redhat.com/show_bug.cgi?id=1448323
This will change the Job status to "warn" when OpenSCAP fails and set the message that is received from image-inspector to be displayed:
Now depends on https://github.com/ManageIQ/manageiq-schema/pull/57 `last_scan_results` table
Depends on https://github.com/ManageIQ/manageiq/pull/15967 for the `LastScanResult` model and association with `ContainerImage`

Scanning job will read oscap erros from image-inspector

---

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
spec/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/stream_spec.rb
spec/models/manageiq/providers/kubernetes/monitoring_manager_spec.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1528955
Completes https://github.com/ManageIQ/manageiq/pull/16635
@moolitayer @cben

ensure monitoring manager is created or deleted on provider update

---

spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb

Refactoring similar to https://github.com/ManageIQ/manageiq-providers-openshift/pull/75.
- compare together to get all differences printed together
- express counts after deletions as subtractions
Also added some checks for volumes after deletions, acounted for my-pod-2 also being deleted, removed some redundant lines.
(VCR coming soon, extracted this for easier review.)
@yaacov @enoodle @moolitayer Please review

refresher_spec: Refactor counts assertions, check volumes after deletions

---

spec/models/manageiq/providers/kubernetes/container_manager_spec.rb

Depending on https://github.com/ManageIQ/manageiq/pull/16755

Using EMS.destroy instead of EMS.orchestrate_destroy

---

locale/fr/ManageIQ_Providers_Kubernetes.po

This PR contains final translation fixes / polishing for Gaprindashvili GA

[GAPRINDASHVILI] Final translations for gaprindashvili

---

spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/rollup_spec.rb

Rollup specs to show our current weak points and that are related
to https://bugzilla.redhat.com/show_bug.cgi?id=1506671

Rollup specs to show our current weak points

---

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb
app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb

Depends on:
We need to use existing relation to project so we build valid query,
otherwise the targeted specs fails.

We need to use existing relation to project so we build valid query

---

app/models/manageiq/providers/kubernetes/container_manager/refresher_mixin.rb

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1469138
Completes https://github.com/ManageIQ/manageiq/pull/16903
@cben @moolitayer

Add a 'Container Project Discovered' event

---

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb
app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb
manageiq-providers-kubernetes.gemspec
spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb

Depends on:
https://bugzilla.redhat.com/show_bug.cgi?id=1504560
@miq-bot add-label enhancement, gaprindashvili/yes

Keep quota history by archiving

---

app/models/manageiq/providers/kubernetes/container_manager/refresher.rb

Remove useless EmsRefresherMixin removed in https://github.com/ManageIQ/manageiq/pull/17472

Remove useless EmsRefresherMixin

---

lib/manageiq/providers/kubernetes/engine.rb

See ManageIQ/manageiq-ui-classic#4496 for primary motivation.

Add plugin display name

---

app/models/manageiq/providers/kubernetes/inventory.rb
app/models/manageiq/providers/kubernetes/inventory/collector.rb
app/models/manageiq/providers/kubernetes/inventory/parser.rb
app/models/manageiq/providers/kubernetes/inventory/persister.rb

Move ManagerRefresh::Inventory to ManageIQ::Providers::Inventory

Move Inventory to ManageIQ::Providers

---

app/models/manageiq/providers/kubernetes/container_manager/inventory_collector_mixin.rb
app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb
app/models/manageiq/providers/kubernetes/container_manager/refresher_mixin.rb
spec/models/manageiq/providers/kubernetes/container_manager/targeted_refresh/targeted_refresh_spec.rb

Move ManagerRefresh to InventoryRefresh
Depends on:

Move ManagerRefresh to InventoryRefresh

---

app/models/manageiq/providers/kubernetes/container_manager/service_instance.rb
app/models/manageiq/providers/kubernetes/container_manager/streaming_refresh_mixin.rb
app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb
app/models/manageiq/providers/kubernetes/inventory/collector/watches.rb
app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb
app/models/manageiq/providers/kubernetes/inventory/persister/definitions/container_collections.rb

Refresh Service Catalog service instances

Refresh Service Catalog service instances

---

app/models/manageiq/providers/kubernetes/container_manager/streaming_refresh_mixin.rb
app/models/manageiq/providers/kubernetes/inventory/collector/watches.rb
app/models/manageiq/providers/kubernetes/inventory/parser/watches.rb

Process delete notices using the targeted_scope

Handle deleted entities

---

CHANGELOG.md

[Changelog] Update for Hammer Beta-1 release

---

app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb

**Issue**: 
Clicking `Cancel Job` on task management screen when task in `waiting...` state will result in error: in `finish is not permitted at state waiting_to_scan`.
It happened because `Job#process_task` sending `:finish` : (https://github.com/ManageIQ/manageiq/blob/e391dec9c57dce99d67555c329906ec2fb71e759/app/models/job.rb#L109) but not all states defined in `ManageIQ::Providers::Kubernetes::ContainerManager::Scanning::Job` can accept  `:finish` 
**Fix**:
allow `:finish` signal to be accepted in any state and behave like `:cancel`
@miq-bot add-label bug
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1640704
**BEFORE**:
**AFTER**:

Override Job#process_cancel to send :cancel signal 

---

manageiq-providers-kubernetes.gemspec

Update to the latest version of kubeclient

Bump kubeclient to 4.0

---

spec/factories/ext_management_system.rb
spec/models/manageiq/providers/kubernetes/container_manager/container_group_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/container_image_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/container_node_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/container_project_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/container_route_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_client_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_legacy_capture_context_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/rollup_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/targeted_refresh/targeted_refresh_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
spec/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin_spec.rb
spec/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/stream_spec.rb
spec/models/manageiq/providers/kubernetes/monitoring_manager_spec.rb

This PR is a followup to ManageIQ/manageiq#18279 where we're updating FactoryGirl to FactoryBot.

Change FactoryGirl to FactoryBot

---

lib/manageiq/providers/kubernetes/engine.rb

Change plugin common methods to class methods

Change plugin common methods to class methods

---

app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb
app/models/manageiq/providers/kubernetes/container_manager/refresher_mixin.rb
config/settings.yml
spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/targeted_refresh/targeted_refresh_spec.rb

Related to: https://github.com/ManageIQ/manageiq-providers-openshift/pull/148

Only support graph refresh

---

app/models/manageiq/providers/kubernetes/container_manager.rb
app/models/manageiq/providers/kubernetes/container_manager_mixin.rb

Add methods to get the required parameters to create a provider and a
method to verify the credentials.
https://github.com/ManageIQ/manageiq/issues/18818

Add params_for_create and verify_credentials

---

app/models/manageiq/providers/kubernetes/container_manager/event_catcher.rb
app/models/manageiq/providers/kubernetes/container_manager/metrics_collector_worker.rb
app/models/manageiq/providers/kubernetes/container_manager/refresh_worker.rb
app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher.rb

Requires https://github.com/ManageIQ/manageiq/pull/19516

Rely on the default implementation of .ems_class

---

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb

https://github.com/ManageIQ/manageiq-ui-classic/issues/7277

Update DDF schema to version 2

---

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
spec/models/manageiq/providers/kubernetes/container_manager_spec.rb

Since we were memoizing a dynamic value, subsequent changes were not reflected.
Depends on https://github.com/ManageIQ/manageiq/pull/20533

Fix bug where settings changes are not reflected in the list

---

.codeclimate.yml
.gitignore
.rubocop.yml
.rubocop_cc.yml
.travis.yml
README.md
Rakefile
bin/ci/after_script
lib/manageiq/providers/kubernetes/engine.rb
lib/tasks/README.md
lib/tasks_private/spec.rake
manageiq-providers-kubernetes.gemspec
spec/spec_helper.rb

Plugin Generator Updates

---

app/models/manageiq/providers/kubernetes/inventory/persister.rb
app/models/manageiq/providers/kubernetes/inventory/persister/container_manager.rb

Use the tag_mapper from the core Persister

---

.codeclimate.yml
.rubocop.yml
.rubocop_cc.yml
manageiq-providers-kubernetes.gemspec

Depends on: https://github.com/ManageIQ/miq_bot/pull/506

Switch to manageiq-style

---

app/models/manageiq/providers/kubernetes/container_manager/options.rb

Fixes https://github.com/ManageIQ/manageiq-providers-kubernetes/issues/413

Consistent usage of CVE Location for i18n

---

app/models/manageiq/providers/kubernetes/container_manager/options.rb

Fixes https://github.com/ManageIQ/manageiq-providers-kubernetes/issues/412

Consistent usage of "No Proxy" for internationalization

---

.rubocop_local.yml
app/models/manageiq/providers/kubernetes/container_manager/kubernetes_event_monitor.rb
app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin.rb
app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/stream.rb
config/settings.yml
lib/manageiq/providers/kubernetes/engine.rb
spec/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin_spec.rb

Move logger initialization and configuration into plugins

Move logger initialization and configuration into plugins

---

.gitignore
config/secrets.defaults.yml
lib/manageiq/providers/kubernetes/engine.rb
spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager/watches_data/new_pod.yml
spec/models/manageiq/providers/kubernetes/container_manager/watches_data/node.yml
spec/models/manageiq/providers/kubernetes/container_manager/watches_data/pod.yml
spec/models/manageiq/providers/kubernetes/inventory/parser/container_manager_spec.rb
spec/spec_helper.rb
spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/refresher.yml

https://github.com/ManageIQ/manageiq/issues/21157

Use pluggable provider secrets

---

app/models/manageiq/providers/kubernetes/container_manager.rb
app/models/manageiq/providers/kubernetes/container_manager/container.rb
app/models/manageiq/providers/kubernetes/container_manager/container_group.rb
app/models/manageiq/providers/kubernetes/container_manager/container_node.rb
app/models/manageiq/providers/kubernetes/container_manager/container_template.rb

Depends on 
@agrare Please review.

Subclassed provider classes should mark the parent as a leaf class

---

app/models/manageiq/providers/kubernetes/container_manager.rb

https://github.com/ManageIQ/manageiq/pull/21224

Add supports :metrics and check for metrics endpoint

---

systemd/manageiq-providers-kubernetes_container_manager_event_catcher@.service
systemd/manageiq-providers-kubernetes_container_manager_metrics_collector@.service
systemd/manageiq-providers-kubernetes_container_manager_refresh@.service
systemd/manageiq-providers-kubernetes_monitoring_manager_event_catcher@.service

part of https://github.com/ManageIQ/manageiq-rpm_build/pull/157
using manageiq properties and still running as root (but very close to switching over to manageiq user)

add properties files to systemd

---

systemd/manageiq-providers-kubernetes_container_manager_event_catcher@.service
systemd/manageiq-providers-kubernetes_container_manager_metrics_collector@.service
systemd/manageiq-providers-kubernetes_container_manager_refresh@.service
systemd/manageiq-providers-kubernetes_monitoring_manager_event_catcher@.service

run services as manageiq user

---

app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb
app/models/manageiq/providers/kubernetes/container_manager/scanning/job/dispatcher.rb
spec/models/manageiq/providers/kubernetes/container_manager/scanning/job/dispatcher_spec.rb

Extract container scanning job dispatcher

---

app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb

Filter out updates for endpoint objects which don't have any information that we care about.  These are updated relatively often (~10sec) and cause a lot of noise.
Follow-up:
* https://github.com/ManageIQ/manageiq-providers-amazon/pull/716

Filter out endpoint notices that have no subsets

---

app/models/manageiq/providers/kubernetes/container_manager.rb

part of https://github.com/ManageIQ/manageiq/pull/21573

converting supported_for_create? to supports :create

---

app/models/manageiq/providers/kubernetes/container_manager.rb

Fix KubeVirt endpoint verification always failing

---

app/models/manageiq/providers/kubernetes/container_manager.rb

Follow-up to: https://github.com/ManageIQ/manageiq/pull/21542
cc @kbrock

Cleanup duplicated supports_authentication? methods

---

spec/models/manageiq/providers/kubernetes/container_manager_spec.rb

Covered:
* Default Endpoint
* valid parameters
* invalid parameters
* verify ssl
* ssl with custom ca
* no ssl verification
* no proxy set
* proxy set
* Metrics Endpoint
* valid parameters
* invalid parameters
* verify ssl
* ssl with custom ca
* no ssl verification
* no proxy set
* proxy set
* Virtualization Endpoint
* valid parameters
* invalid parameters
* NOTE no verify ssl or proxy options are passed here

Add specs covering K8s `.verify_credentials`

---

app/models/manageiq/providers/kubernetes/container_manager.rb
spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/rollup_spec.rb
spec/models/manageiq/providers/kubernetes/container_manager_spec.rb

Support for both of these was removed previously but some references were missed during the cleanup.
https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/518
https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/453

Delete unused hawkular/alerts endpoints

---

.github/CODEOWNERS

As much as we love cben I bet he's tired of getting these notifications

Remove cben from CODEOWNERS

---

lib/manageiq/providers/kubernetes/engine.rb

Depends indirectly on: https://github.com/ManageIQ/manageiq/pull/23509

Drop to_s on engine paths
