spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_client_gauges_query.yml
Because the hawkular ruby client now sends extra parameters in the URL.
This was fixed manually.
=> Fixing cassette

app/models/manageiq/providers/kubernetes/container_manager/metrics_collector_worker.rb, app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
Starting with k8s since container_manager_mixin is shared with openshift.
We will then need to do one of:
- copy emses_in_zone to openshift's metrics_collector_worker.rb
OR
- create a common component for both metrics collectors
supports_metrics? aims to be replaced by a support feature.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1437138#c0
=> Avoid metrics collection workers unless endpoint

manageiq-providers-kubernetes.gemspec
Add runtime dependency on hawkular-client.
=> Moving hawkular-client dependency from manageiq-gems-pending

app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
This will make sure that `image_ref` will contain the image digest if available (from docker-pullable resource if available or and local docker daemon). This will make it easier to compare images by `image_ref`.
=> parse docker daemon digest and set it in image_ref

app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb, config/settings.yml, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
This adds an option to configure timeout for container ssa jobs:
- With the global settings file, under "container_scanning" in the field "scanning_job_timeout"
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1447672
=> configurable timeout for SSA

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb, config/settings.yml, spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
Ability to constrol kubeclient timeouts from settings.yml
openshift half: ~~https://github.com/ManageIQ/manageiq-providers-openshift/pull/8~~ unnecessary on master given https://github.com/ManageIQ/manageiq-providers-openshift/pull/7, but will add it in backports.
Tested:
https://bugzilla.redhat.com/show_bug.cgi?id=1440950
@miq-bot add-label euwe/yes, fine/yes (actually we plan a 5.7.1 hotfix but I suppose we also want normal backports, so customer uprading will not lose hotfix functionality?)
@moolitayer @agrare Please review.
=> kubernetes_connect: add timeout settings

manageiq-providers-kubernetes.gemspec
Previously, we got this dependency implicitly through manageiq,
kubeclient, etc.  Since we use this heavily in tests here, we should
state our reliance on this gem.
Needed for: https://github.com/ManageIQ/manageiq/pull/15096
=> Make recursive openstruct an explicit dependency

app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb
**Deiscription**
We currently insert a wrong place-holder value to the `ContainerImage#registered_on` field `:registered_on => Time.now.utc`
This PR remove this place-holder value from the Kubernetes provider, and insert the correct value in a new PR in the OpenShift provider.
Issue: https://github.com/ManageIQ/manageiq-providers-kubernetes/issues/17
Openshift PR: https://github.com/ManageIQ/manageiq-providers-openshift/pull/17 
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1454329
=> Move image registered_on field to openshift provider

app/models/manageiq/providers/kubernetes/container_manager/entities_mapping.rb
There are instances where are "reverse" lookup of entity mappings is desirable.  This is needed for pull requests:
https://github.com/ManageIQ/manageiq/pull/14798
https://github.com/ManageIQ/manageiq-providers-openshift/pull/2
https://github.com/ManageIQ/manageiq-automation_engine/pull/7
=> Provide a reverse lookup for provider entities

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
Before this change the user displayed in `tasks-> All Tasks` was always system.
After the user should be the logged in user initiating the scan
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=1439652
=> Set container scanning user

manageiq-providers-kubernetes.gemspec
Moving from https://github.com/ManageIQ/manageiq-gems-pending/blob/master/manageiq-gems-pending.gemspec
=> Add Dependency on image-inspector-client gem

manageiq-providers-kubernetes.gemspec
Moving from https://github.com/ManageIQ/manageiq-gems-pending/blob/master/manageiq-gems-pending.gemspec
=> Add Dependency on kubeclient gem

app/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin.rb, app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb
> *Toi, toi, toi!* (from an old superstition): An exclamation after a statement or declaration in order to prevent a hex from being put on it, accompanied by knocking on a wooden object such as a **table** with one’s knuckles.
> — http://forward.com/culture/15158/spit-your-way-to-safety-toi-toi-toi/ [**emphasis** mine]
> 
> The origin of the custom may be in Germanic folklore, wherein supernatural beings are thought to live in trees, and can be invoked for protection.
> — https://en.wikipedia.org/wiki/Knocking_on_wood
In our case the `obj["table"][:namespace]` incantation summons the tree of hashes that dwells inside a RecursiveOpenStruct, to ward off a monkey patch.
The custom to say `obj["table"][:namespace]` probably arose because `obj[:namespace]` didn't work either until …
=> Get rid of unnecessary magic ["table"] RecursiveOpenStruct access

app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb
We want to formulate graph refresh in a way that can process partial info independently.
Some pieces are still missing to actually achieve that, but it's clear we need to untangle parsing logic from the `@data_index` writes and reads that currently pervade it.
This PR refactors the *current* parser in that direction.
`parse_foo` methods will become pure functions processing their piece of the inventory;
only the `get_foos` methods will read and write `@data_index` to link the resulting hashes
(`get_foos_graph` methods introduced in #30 will do linking differently; I matching changes for them but let's review the non-graph part here.)
- Exception: image & registry parsing still *reads and writes* `@data_index` in-place.  I can live with that for now, will revisit it later.
cc @zakiva …
=> Separate data_index lookups from parsing

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
Calculating user in `raw_scan_job_create` is too late since it is called from automate and always evaluates to admin at that point.
https://bugzilla.redhat.com/show_bug.cgi?id=1460754
=> Pass userid before going to automation

spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
Disconnect tests added in #44 were expecting ems_id to become nil,
which doesn't happen after soft delete https://github.com/ManageIQ/manageiq/pull/15251.
Fixed by asking `.archived?` instead.
=> Update disconnection test to understand soft delete

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb, app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
Followup to #30, implements most entity links in get_*_graph.
Now kubernetes graph refresh passes full refresher tests!
- Except tagging by labels which is skipped.
A few things starting with _ indicate still missing functionality that is not covered by refresher_spec, will add tests later.
Mostly using `lazy_find` by secodary indexes on name or (namespace, name).
(enabled by https://github.com/ManageIQ/manageiq/pull/15447)
- Still using `@data_index` for images & registries.
- Used a local hash similar to data_index for endpoint/service matching.
=> Graph refresh: links between entities

spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb, spec/spec_helper.rb
Kubeclient builds `RecursiveOpenStruct`s that also `recurse_over_arrays`:
https://github.com/abonas/kubeclient/blob/v2.4.0/lib/kubeclient/common.rb#L166
Some of our parser tests contain arrays; in some cases we compensate with nested call `RecursiveOpenStruct.new` calls, in some we pass arrays of hashes instead.
This PR ensure kubeclient-like inputs everywhere.
The helper function name was shamelessly engineered to avoid reindenting ;-) but I can easily change it if someone wants.
@miq-bot add-labels refactoring, test
@moolitayer @enoodle @zakiva please review.  I can do openshift too if you like this.
=> Let ROS recurse_over_arrays, matching kubeclient

app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb
It is not used anymore since the move to use readinessProbe in https://github.com/ManageIQ/manageiq/pull/14578
=> remove obsolete pod_health_poll

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb, spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
The kubernetes provider supports metrics from prometheus, currently the `supports_metrics?` fails to recognize this endpoint.
This PR fixes that.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1470537
=> Fix support_metrics function to include prometheus

spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb
Those actually become part of the words!
Kudos rubocop for calling this out.
Test worked because we had them in both input and expected output.
@miq-bot add-label test, technical debt
=> Shouldn't have quotes and commas inside %w(...)

spec/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
Followup to #58.
Not touching MockImageInspectorClient as real ImageInspectorClient doesn't use recurse_over_array (its data don't contain arrays anyway).
@miq-bot add-labels refactoring, test
=> recurse_over_array in more places representing KubeClient outputs

spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_client_spec.rb
Should fix test failures of https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/38
=> Use k8s provider in k8s tests

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb, app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, app/models/manageiq/providers/kubernetes/container_manager/refresher.rb, config/settings.yml, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
Initializing the openshift inv_collections arguably belongs in openshift
repo, but not bothering with move as @agrare has plans to move them both
to core repo.
RFE: https://bugzilla.redhat.com/show_bug.cgi?id=1470021
=> Changes needed for openshift graph refresh

app/models/manageiq/providers/kubernetes/monitoring_manager_mixin.rb
Like other managers with parents, we must `allow_nil` to pass 
manageiq-ui-classic's `tree_node_spec.rb` creation with out a parent obeject (which should never happen in real life). Reproduce using `ManageIQ::Providers::Openshift::MonitoringManager.new` (as @himdel pointed out)
=> Allow nil parent for tests

spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_spec.rb
The `.find_by` instead of `.first` will make the tested targets stable and matching the VCR even if refresh record order changes.
It also happens to fix VCR errors following #42, but not because of order.
`.first` returned same record as `.find_by` but behavior differed!
The reason is that without `.reload` after refresh, ActiveRecord caches were stale, with unpredictable results...
(Exact queries during refresh changed in #42, with the result that `pod = @ems.container_groups.first` did not go to DB, and `pod.containers` weirdly returned same container twice.)
=> Fix "unused HTTP interactions", make test more robust

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb, app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
Depends on https://github.com/ManageIQ/manageiq/pull/15393
@enoodle @zakiva Please review
cc @simon3z @moolitayer @cben
=> unify container and container definition

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb, app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, app/models/manageiq/providers/kubernetes/inventory.rb, app/models/manageiq/providers/kubernetes/inventory/persister.rb, app/models/manageiq/providers/kubernetes/inventory/persister/container_manager.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
Add Persistor with configurable saver strategy. Encapsulating ICs to Persistor and exposing the options to Settings. Testing both ;default and :batch strategies
Check with https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/73/files?w=1 to filter out the whitespace changes
=> Add persistor with configurable saver strategy

app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb
Depends on and completes https://github.com/ManageIQ/manageiq/pull/15180
More info: https://kubernetes.io/docs/tasks/administer-cluster/cpu-memory-limit/
```
~$ oc describe pod nginx-1-deploy
Name:			nginx-1-deploy
Namespace:		aris-project
Security Policy:	restricted
Node:			---
Start Time:		Sun, 21 May 2017 12:18:34 +0300
Containers:
deployment:
...
Limits:      <-------------------------------------
cpu:	300m
memory:	200Mi
Requests:
cpu:		200m
memory:		100Mi
State:		Terminated
Reason:		Error
Exit Code:	1
Started:		Sun, 21 May 2017 12:18:40 +0300
...
```
@simon3z @cben @moolitayer
=> collect container definition limits

app/models/manageiq/providers/kubernetes/container_manager/container_template.rb, app/models/manageiq/providers/kubernetes/container_manager/container_template_mixin.rb
Part of ManageIQ/manageiq#15523.
Blocks https://github.com/ManageIQ/manageiq-providers-openshift/pull/28.
@miq-bot add_label refactoring
=> Move kube/openshift specific template code into its provider directory.

app/models/manageiq/providers/kubernetes/container_manager.rb, app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb, app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb
I assumed in this code the model used when defining these collections is same model as the `parent` for which we are looking them up, which is wrong given STI.
This fixes errors in manageiq-providers-openshift repo:
```
can't save: missing @inv_collections[[:custom_attributes_for, "ContainerTemplate", "labels"]]
can't save: missing @inv_collections[[:custom_attributes_for, "ManageIQ::Providers::Kubernetes::ContainerManager::ContainerTemplate", "labels"]]
```
following https://github.com/ManageIQ/manageiq-providers-openshift/pull/28 and related PRs.
I'm still seeing other errors in openshift specs locally, but this gets us closer to green...
@lfu @moolitayer @Ladas please review.
=> Fix fallouts from ContainerTemplate STI

app/models/manageiq/providers/kubernetes/container_manager.rb, app/models/manageiq/providers/kubernetes/container_manager/options.rb, app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb, app/models/manageiq/providers/kubernetes/container_manager_mixin.rb, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
Based on https://github.com/ManageIQ/manageiq/pull/15398
This will use the options field for per-provider configuration in image scanning.
Also, This will try to use the http_proxy set in the options to connect to the provider instead of the one defined in the settings file. Originally it was planned to have `https_proxy` and `no_proxy` options as well for the connection to the provider but as they are not used currently I left them out.
=> Using the new options for image-scanning options

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb, app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
Added refresher specs for CVs, PVs, PVCs.
Testing those in the new easier-to-reproduce VCRs.  I was lazy and avoided re-recording but relying on some hawkular/cassandra stuff that's not in the template — but should be pretty stable.
@miq-bot add-label bug, test
Graph refresh RFE: https://bugzilla.redhat.com/show_bug.cgi?id=1470021
=> Volume-related graph refresh fixes & VCR specs

app/models/manageiq/providers/kubernetes/container_manager/container_template_mixin.rb, app/models/manageiq/providers/kubernetes/container_manager/entities_mapping.rb
We can now use the [entities mapping](https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/master/app/models/manageiq/providers/kubernetes/container_manager/entities_mapping.rb)  to map the objects kind to a miq class after instantiation. 
Moved from https://github.com/ManageIQ/manageiq/pull/13619
@moolitayer @simon3z Please review
=> Use EntitiesMapping in Container Template

manageiq-providers-kubernetes.gemspec
Recently, we released a new version of Hawkular, doing some breaking changes in the process. The changes are mainly related to error handling, so there's nothing to change on the provider.
However, if you do want to take advantage of the new features, now you can catch any and all Hawkular errors by rescuing `Hawkular::ConnectionException` for connection-related issues, `Hawkular::ArgumentError` for improper usage of the library, and `Hawkular::Exception` as a catch-all.
Depends on: https://github.com/ManageIQ/manageiq-providers-hawkular/pull/26
=> Update Hawkular version

spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/refresher.yml
This cassette shows 1 of 3 componentstatus.message field containing a sub-*hash* `{"health":"true"}` rather than a string.  I can't reproduce that on any live cluster nor cassette, it's always a string.
Evidence it was actually the *string* `'{"health":"true"}'`:
- refresh_parser_spec from [same commit](https://github.com/ManageIQ/manageiq/pull/4891) has `'{...}'` string!
- https://github.com/kubernetes/kubernetes/issues/16721#issue-114767348 by dkorn from same time shows `'{...}'` string
- https://github.com/openshift/origin/issues/5570#issuecomment-153020811 by another person from same time shows `'{...}'` string
- api/types.go had `message String` ever since it was added
https://github.com/kubernetes/kubernetes/commit/951a125751d5985750c82e919ab151a117bc5a94
- I see other signs this …
=> Manually edit cassette that I believe was manually misedited

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb
Remove use_ar_object to speedup the saving, it's not needed
anymore due to the latest changes in the saver engine (https://github.com/ManageIQ/manageiq/pull/15761).
=> Remove use_ar_object to speedup the saving

app/models/manageiq/providers/kubernetes/container_manager/kubernetes_event_monitor.rb
See the same change in ovirt:
https://github.com/ManageIQ/manageiq-providers-ovirt/pull/80
Replaces #95 
It was added originally back in 2011 in manageiq:
946657b11a0a65abbcdca9975206d71f7c2b7afc
This was actually copied from the vmware vim monitoring events
code from 2009: 22a911716b40428b6d822f0f1e95aabd022e59c9
```
def monitorEvents
raise "monitorEvents: no block given" if !block_given?
trap(:TERM) { $log.info "monitorEvents: ignoring SIGTERM" }
...
```
First of all, trap with logging doesn't work since ruby 2.0+:
```
irb(main):001:0> require 'logger'
=> true
irb(main):002:0> trap(:TERM) { Logger.new("stdout").info
"EventMonitor#start: ignoring SIGTERM" }
=> "DEFAULT"
irb(main):003:0> `kill #{Process.pid}`
log writing failed. can't be called from trap context
=> ""
```
See …
=> Remove seemingly unnecessary ignoring of SIGTERM

spec/spec_helper.rb, spec/support/array_recursive_ostruct.rb
Specifically will allow
https://github.com/ManageIQ/manageiq-providers-openshift/pull/35 to
reuse `array_recursive_ostruct` helper from here, instead of duplicating it.
@miq-bot add-label test
=> A spec/support/ directory to be reused by openshift repo

app/models/manageiq/providers/kubernetes/container_manager/container_template_mixin.rb
Depends on https://github.com/ManageIQ/manageiq/pull/15863
Converts the Container Template Parameters that are passed to instantiate method to hashes before passing them to openshift for template processing. The new hashes include only relevant attributes for instantiation instead of the whole active record object that has some irrelevant data. 
Moved from https://github.com/ManageIQ/manageiq/pull/15587
=> Container Template: convert params to hashes

app/models/manageiq/providers/kubernetes/container_manager/options.rb
Based on https://github.com/ManageIQ/manageiq/pull/15799#pullrequestreview-56271746 I suggest renaming this function for clarity.
=> rename provider_settings to options_description

app/models/manageiq/providers/kubernetes/container_manager/refresher_mixin.rb
Depends on:
Add ContainerImage raise event post processing job, queuing
the raise event as a background job, since it does not
belong under the refresh.
=> Add ContainerImage raise event post processing job

app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb
#kubernetes part of https://github.com/ManageIQ/manageiq/pull/14662 after repo split.
This will have to be merged before openshift part https://github.com/ManageIQ/manageiq-providers-openshift/pull/9.
Strawman alternative/baseline for https://github.com/ManageIQ/manageiq/pull/14628.
Will allow to still get_container_images=true, but instead of saving metadata (labels etc) on all images openshift gave us, save it only for images that have been mentioned by pods.
Here called `store_new_images` because this function doesn't have the context to understand which images are "used".
For `store_unused_images`=false setting, it'll be called twice:
- from parse_pods with true, adding all images
- from parse_openshift_image with false, only enriching previous images
cc @agrare @enoodle @zeari
=> Option needed for new ems_refresh.openshift.store_unused_images setting

app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb
```
[----] E, [2017-08-08T05:55:00.221227 #15805:1041130] ERROR -- : [NoMethodError]: undefined method `[]' for nil:NilClass  Method:[rescue in block in refresh]
[----] E, [2017-08-08T05:55:00.221475 #15805:1041130] ERROR -- : /var/www/miq/vmdb/app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb:767:in `parse_image_name'
```
https://bugzilla.redhat.com/show_bug.cgi?id=1484337
=> Skip invalid container_images

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
Currently a miq queue request to authenticate a container provider will not authenticate all endpoints, missing endpoints are "hawkular" and "prometheus"
**Screenshots**
Before fix
After fix
=> Add mising metrics authentication

app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
depends on:
https://github.com/ManageIQ/manageiq-schema/pull/60
https://github.com/ManageIQ/manageiq/pull/15932
@cben @moolitayer @zakiva Please review
cc @simon3z we are going to need this relation for chargeback so we can identify pvc's that are not connected to pods but are connected to a project
=> Save persistent volume claim to project relation

config/settings.yml
Same as https://github.com/ManageIQ/manageiq-providers-openshift/pull/48, can be merged in either order.
There are some loose ends (notably tag mapping missing)
but we want to get more testing from developers using it.
tracking issue #27
RFE https://bugzilla.redhat.com/show_bug.cgi?id=1470021
=> Enable graph refresh (batch strategy) by default

app/models/manageiq/providers/kubernetes/container_manager/container_template_mixin.rb
Extracted from: https://github.com/ManageIQ/manageiq/pull/15406
Allowing the `instantiate` method to receive labels as an argument so that each created object will be tagged with these labels during instantiation.
cc @moolitayer @simon3z
=> Container Template: Allow instantiation with object_labels

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture.rb
We collect `average kb usage per second` from the external metrics data base.
When we insert data in the internal metrics data base we declare it to be 0.5 of `average datagrams per second`.
This may lead to wrong data presented to the end user, for example, if we collect 80 kb/sec the user may see 160 datagrams/sec [the *2 is for 0.5 to value conversion]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1495733
=> Fix net_usage_rate_average units

app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1481230
For reference, `unqueue_all_signals` is defined on the same file here: https://github.com/enoodle/manageiq-providers-kubernetes/blob/6bf8ad2a024c430207085e481c8e7c87643ed613/app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb#L308
=> Scanning::Job always cleanup all signals in cleanup

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1483590
Related PR: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/119
Adding the scanned image name to the task name:
=> Image scanning: Add image name to task name

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture.rb, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture_spec.rb
an empty set means there is no data and the platform will not
try to collect the data again. Unless a manual gap detection is
performed.
see https://github.com/ManageIQ/manageiq/blob/91d3ef4189e8b9e9d2225b758082d52f688926da/app/models/metric/ci_mixin/capture.rb#L193-L195
and
https://github.com/ManageIQ/manageiq/blob/91d3ef4189e8b9e9d2225b758082d52f688926da/app/models/metric/ci_mixin/capture.rb#L56-L58
fixes
https://bugzilla.redhat.com/show_bug.cgi?id=1411894
@yaacov please have a look if that makes sense for you
cc @agrare
=> dont return an empty set when something goes wrong

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
Depends on https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/105. 
This PR removes the backward compatibility kept in https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/105. In case of creating a scanning job with image instance (instead of class) an explicit exception will be raised.
=> Fail on creating scanning job with image instance

app/models/manageiq/providers/kubernetes/container_manager/entities_mapping.rb, app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb, app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, app/models/manageiq/providers/kubernetes/container_manager/refresher_mixin.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb, spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_refresh.yml, spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_refresh.yml, spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/refresher.yml, spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/refresher_after_deletions.yml, spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/refresher_before_deletions.yml
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1485431 
Schema: https://github.com/ManageIQ/manageiq-schema/pull/79
Core: https://github.com/ManageIQ/manageiq/pull/16055
UI: https://github.com/ManageIQ/manageiq-ui-classic/pull/2246
=> Drop Container Component Statuses

app/models/manageiq/providers/kubernetes/container_manager/event_parser_mixin.rb
The event handler expects the ems_ref to be prefixed by the object type,
not using the raw ems_ref.  This is causing issues adding a real ems_ref
for an event because the process_container_entities_in_event! method is
clearing the key.
=> Prefix ems_ref with object type in event hash

app/models/manageiq/providers/kubernetes/container_manager/options.rb, app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb, config/settings.yml, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
This will use thes settings as global options when no per-provider options are set
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1459555
=> adding cve_url and image_tag to global image_inspector settings

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb, app/models/manageiq/providers/kubernetes/monitoring_manager.rb, app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher.rb, app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner.rb, app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin.rb, app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/stream.rb, app/models/manageiq/providers/kubernetes/monitoring_manager_mixin.rb, app/models/manageiq/providers/kubernetes/prometheus/message_buffer_client.rb, config/settings.yml, spec/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin_spec.rb, spec/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/stream_spec.rb, spec/models/manageiq/providers/kubernetes/monitoring_manager_spec.rb, spec/vcr_cassettes/manageiq/providers/kubernetes/monitoring_manager.yml, spec/vcr_cassettes/manageiq/providers/kubernetes/monitoring_manager/event_catcher/stream.yml
Issue: https://github.com/ManageIQ/manageiq/issues/14238
See issue for setup
=> Prometheus alerts

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb
Proposed replacement for #106 — tweaked the initialize_custom_attributes_collections interface per review discussion.
Add parent inventory collections to ensure proper disconnect order in the case that collection is empty and we can't compute dependencies.
Fixes bug with `save_unused_images: false` mode deleting existing child custom_attributes records (https://github.com/ManageIQ/manageiq-providers-openshift/pull/46, which also needs a tiny tweak to work with this)
=> Add parent inventory collections to ensure proper disconnect order

app/models/manageiq/providers/kubernetes/container_manager/refresher_mixin.rb
Depends on:
Changed interface for post refresh in core, we pass Persister object
instead of Array<InventoryCollection>
=> Changed interface for post refresh

spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
There was a test added which assumed we do not nil out the container_project from a pod, but this is not committed yet.
This reverts the commit that changed the test expectations.
=> Fix kubernetes refresher spec tests

spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb
ManageIQ has its own `have_attributes` which has diverged from upstream rspec's.  It'll go away at some point.
This fixes one non-standard usage this repo had.
(Thanks to https://github.com/ManageIQ/manageiq/pull/16188 warnings)
before: https://travis-ci.org/ManageIQ/manageiq-providers-kubernetes/jobs/294409726
after: https://travis-ci.org/cben/manageiq-providers-kubernetes/jobs/294618442
providers-openshift repo is clean.
@miq-bot add-labels test, technical debt
=> Fix non-standard `have_attributes` usage warnings

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb, app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin.rb, app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/stream.rb, spec/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin_spec.rb, spec/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/stream_spec.rb
- Enable alerts on the new events
- Dropped the timestamp hack (no longer needed after https://github.com/ManageIQ/manageiq/pull/16104)
Part of Prometheus Alert integration:
https://github.com/ManageIQ/manageiq/issues/14238
Related to
https://github.com/ManageIQ/manageiq/pull/16310
=> Collect ems targeted Prometheus events

spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
Fix spec since we do not delete project foreign_key when
we disconnect pod.
Needed for fixing CI after the https://github.com/ManageIQ/manageiq/pull/16302 is merged
=> Fix spec since we do not delete project foreign_key

app/models/manageiq/providers/kubernetes/container_manager/inventory_collector_worker.rb
Vintage :TM: refresh for container providers doesn't reconnect container
images so having duplicate targets queued by the
InventoryCollectorWorker can lead to duplicate records.  For this reason
we want to disable the InventoryCollectorWorker if
`:inventory_object_refresh` is disabled.
=> Don't start CollectorWorker if Graph Refresh disabled

app/models/manageiq/providers/kubernetes/container_manager/inventory_collector_mixin.rb, config/settings.yml
This adds a setting to the InventoryCollectorWorker which allows for only DELETED pod notices to be sent, thus reducing the traffic hitting MiqQueue.
=> Add a setting to only send DELETED notices

config/settings.yml
Due to the large payload size generated by the watch notices disable the collector worker by default until payloads can be moved to BinaryBlobs table
=> Disable inventory collector worker by default

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb, spec/models/manageiq/providers/kubernetes/container_manager/targeted_refresh/targeted_refresh_spec.rb
Make sure targeted refresh does not duplicate entities by implementing the reconnect logic for ContainerGroup, Container and ContainerImage models.
Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1507899
Fixes issue:
https://github.com/ManageIQ/manageiq-providers-kubernetes/issues/103
=> Make sure targeted refresh does not duplicate entities

app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin.rb, app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/stream.rb, spec/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin_spec.rb
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1507990
Currently ManageIQ collects alerts with annotation `MiqTarget=ContainerNode|ExtManagementSystem` and uses the annotation to find the target object.
Suggested: ManageIQ collects all generated alerts[1] and always attaches incoming alerts to the ems
Note: a user can still specify `MiqTarget=ContainerNode` to attach a specific alert to a node.
- If the node cannot be found for some reason,  the alert will fallback on the ext.
- There should never be a mismatch, even if we have a Node alerts with several firing instances defined on the same node (e.g one instance for each container in the node).
The screen would show them as duplicated alerts.
[1] you can still ignore alerts by annotating them with `miqIgnore=true`
=> Prometheus Alert flow changes

app/models/manageiq/providers/kubernetes/container_manager/inventory_collector_worker.rb
The has_required_role? method wasn't calling the base
MiqWorker#has_required_role? leading to all workers in the zone running
the inventory collector.
Depends: ~~https://github.com/ManageIQ/manageiq/pull/16415~~
=> Fix Inventory Collector has_required_role?

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_mixin.rb, config/settings.yml
Description
Metrics collection from OCP 3.7 using Prometheus may hit timeout while collecting metrics.
a. the default timeouts are too small
b. users can not set new timeout values to fit their system
This PR uses the settings needed to adjust the timeouts.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1511341
=> Use Proetheus timeouts form settings

app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1508372
Depends on: 
https://github.com/ManageIQ/manageiq-schema/pull/74 - Merged
https://github.com/ManageIQ/manageiq/pull/16026 - Merged
@miq-bot add_label enhancement
@simon3z @zeari Please review
=> Parse requests and limits for Persistent Volume Claim

spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
Split from #162
- Use factory for more accurate test, matching UI-created mapping categories.
Previous test didn't set read_only nor used 'kubernetes:' prefix,
failed with attempted retagging implementation https://github.com/ManageIQ/manageiq/pull/16449
and will fail with its upcoming replacement.
- Test that we don't remove user-assigned tags.
=> Improve tag mapping specs

app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin.rb
Currently when an incident starts (e.g Container Node High Memory Usage) we get notified ONCE according to our selected notification method. We will be notified again when the incident is resolved.
For our use case (operators monitoring a cluster) one would want to keep getting alerts on an open issue until it is fixed. 
Prometheus keeps sending out messages when an incident is open but we created only one EmsEvent out of them since events with a similar time stamp mask each other and Prometheus startsAt is the same for alerts coming from the same incident.
ems_ref should still consider startsAt since that would still make sure we are only creating one MiqAlertStatus per incident.
=> Enable getting multiple alert for an incident

app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
Meant to report that image-inspector failed to acquire the image,  this will read ImageAcquireSuccess, ImageAcquireError and abort the job if needed with the error reported from image-inspector.
Based on image-inspector change from: https://github.com/openshift/image-inspector/pull/82
Currently (Before these two fixes) when Image-Inspector is failing to acquire the image it will exit and the Job on the ManageIQ side will wait until timeout is reached for the information to be served.
When the image-inspector image is updated with this change but ManageIQ is running without this patch the error message will look similar to this:
```
cannot analyze image 172.30.6.216:5000/test2/origin-ruby-sample@sha256:050b667cd1c1d5c5781f0c8ee5763ab5ef26e3a15c4d85cf7d143c1513890cec with id 172.30.6.216: …
```
=> read image acquiring status

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb, app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
Depends on:
(~~OR revive reverted https://github.com/ManageIQ/manageiq/pull/16449~~)
Overview/plan issue: #126
(added test for not removing user-assigned tag has been extracted to #170 and already merged)
@miq-bot add-label enhancement gaprindashvili/yes
https://bugzilla.redhat.com/show_bug.cgi?id=1470021
@Ladas @moolitayer please review
=> Tag mapping in graph refresh

spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_spec.rb
Existing test doesn't work because instance vars were reset for each test, so we do 3 refreshes anyway.
Replaces #184 and #185 that explored ways to make it work but were deemed not worth it.
Overhead of doing 3 refreshes is only 1 sec (5.5s instead of 4.5s).
@miq-bot add-label test, refactoring
@yaacov please review
=> Remove non-working attempt to do refresh only once

app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb
Make sure Container has always the right STI type. Before, the
missing image could cause the STI type is Container, which
made metrics capture fail.
Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1517676
=> Make sure Container has always the right STI type

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture.rb, app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/capture_context_mixin.rb, app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context.rb, app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context.rb, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture_spec.rb
TL;DR This PR change query rate from  Hawkular/Prometheus to 60s.
Metrics are scraped from k8s/openshift once every 30s into Hawkular/Prometheus.
Currently we query data from Hawkular/Prometheus every 20s, this create a response with missing data.
After discussion we decided to query from Hawkular/Prometheus every 60s, because it is a multiple of base rate (e.g. 30s) and allow for missing heartbeat once in a while.
Removed from #159 
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1524183
=> Make capture interval a multiple of 30s

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb, app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
Kubernetes namespaces (aka openshift projects) may have quotas.
Each quota may have one or more *scopes*, which we didn't store before but should:
https://kubernetes.io/docs/concepts/policy/resource-quotas/#quota-scopes
https://docs.openshift.com/container-platform/3.7/admin_guide/quota.html#quota-scopes
https://bugzilla.redhat.com/show_bug.cgi?id=1504560
@zeari @enoodle please review.  VCR tests coming in later PR.
=> Parse and save quota scopes

app/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin.rb, spec/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin_spec.rb
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1496179
This makes `event_data[:event_type]` equal `POD_FAILED` 
instead of  `CONTAINER_FAILED` 
part of ManageIQ/manageiq#16583
@cben @moolitayer @enoodle Please review
=> Make container events belong to pod

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb
Blacklisting was a lazy way to discard unimplemented tags (analogous to `h.except!(:tags)` I removed in few other places), unnecessary after https://github.com/ManageIQ/manageiq-providers-openshift/pull/64.
https://bugzilla.redhat.com/show_bug.cgi?id=1470021
=> Drop :tags blacklist, refresh now extracts :tags to separate collection

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context.rb, app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_mixin.rb, manageiq-providers-kubernetes.gemspec, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_spec.rb
We want to leverage the new Prometheus API gem, for metrics collection.
BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1468251 - Use Prometheus Metrics Ruby client
Note: this is the second part of https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/132
=> Use prometheus client instead of faraday

app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
When using images from an external registry that requires authentication we have to create a secret [1] to pull the images when creating the pods.
To scan the images originating from this registry we will have to add this secret (or a similar one) to the `inspector-admin` service account in the `management-infra` namespace. [2]
This PR will make sure that the additional `imagePullSecrets` from the `inspector-admin` SA are passed on to the image-inspector to try authenticate to the registry.
BZ Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1529510
[1] https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
[2] https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#adding-imagepullsecrets-to-a-service-account
=> support multiple imagePullSecret secrets for inspector-admin SA

spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb
Followup to #177.  As discussed there, testing actual `type` set in DB in refresher_spec might be best, but it turned out harder than I thought to capture pods without status in VCR.  A pod with bad image does get a status, with `waiting` state.  (Maybe requesting resources above quota to keep it pending would work?)
Instead, I captured various states a pod goes through from `oc get pods --watch --show-all --all-namespaces -o json` into refresh_parser_spec.
(Tip: `jq 'select((.spec.containers | length) > (.status.containerStatuses | length))'` finds states with missing statuses.)
We already have some tests for parse_container_status/state, but the bug here
Wasn't sure what to test, for now included all states but only tested STI types.
Verified test failed before #177:
```
parse_pod
sets …
```
=> Tests for parse_pod, specifically for STI type if missing pod status

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context.rb
If no metrics where pushed into Hawkular ( a problem with provider setup (*) ), it will return a valid answer (HTTP 200) with no data.
(*) On a system that was configured correctly we will get data with `empty=true` fields. 
On such systems we currently get:
NoMethodError: undefined method `keys' for nil:NilClass
This PR check that we have data in the response before trying to parse it.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1530627
=> Don't try to parse empty data set returned from hawkualr

app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb
This works around bug in classic refresh where casting didn't happen,
so we can proceed with container quota archiving independently of
https://github.com/ManageIQ/manageiq/pull/16723
This way backporting of that fix can be decided independently.
https://bugzilla.redhat.com/show_bug.cgi?id=1504560
@miq-bot add-label enhancement, gaprindashvili/yes
@yaacov @zeari @moolitayer Please review.
Didn't add tests, because not sure if I should test anything here,
but will have tests for no unnecessary archiving in the archiving PR.
=> Cast quota values to float in parser, to match float columns

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
Add a method to queue reading of metrics.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1527877
Target: 5.9.1
=> Add a queue metrics capture method to container manager

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1460401
@cben @moolitayer Please review
Trying to come up with specs
@miq-bot add_label gaprindashvili/yes
=> Archive nodes in graph refresh

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb, app/models/manageiq/providers/kubernetes/virtualization_manager_mixin.rb, spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
The kubevirt provider will be managed as a virtualization manager under
the container managers.
The endpoint and authentication of kubevirt will be selected by
:kubevirt role and authkey.
This PR depends on https://github.com/ManageIQ/manageiq/pull/16721.
Additional related PRs:
UI PR:
https://github.com/ManageIQ/manageiq-ui-classic/pull/3143
kubevirt provider PR:
https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/6/
=> Support KubeVirt provider

app/models/manageiq/providers/kubernetes/container_manager.rb, app/models/manageiq/providers/kubernetes/container_manager/container_group.rb
This is a continuation of the work started in https://github.com/ManageIQ/manageiq/pull/16596 where we want to migrate display model names from locale/en.yml into particular models, where we'll use standard gettext. Main goal here is to make this one aspect of our application pluggable.
Core PR: https://github.com/ManageIQ/manageiq/pull/16836
=> Migrate model display names from locale/en.yml to plugin

app/models/manageiq/providers/kubernetes/monitoring_manager_mixin.rb
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1535941
The problem is that the monitoring manager looks for a default endpoint which it does not have. 
The parent provider has that endpoint and validates it anyway so no need for the monitoring manager to validate it.
Another solution could be to delegate the default endpoint from the monitoring_manager to the parent provider or just regard the alert endpoint as the default endpoint for monitoring.
Monitoring manager has some prep work for the latter: https://github.com/manageiq/manageiq-providers-kubernetes/blob/master/app/models/manageiq/providers/kubernetes/monitoring_manager_mixin.rb#L59
but ext_management_system doesnt take it into account:
https://github.com/manageiq/manageiq/blob/master/app/models/ext_management_system.rb#L295 …
=> Skip hostname validation for monitoring manager

app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin.rb, spec/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1536087
Match changes in https://github.com/openshift/origin/pull/17608/files
=> Change alert definition meta

app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
Due to changes in [1], the field `ImageAcquireSuccess` is not being used anymore
[1] https://github.com/openshift/image-inspector/pull/82
=> only use the ImageAcquireError field

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture.rb, app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context.rb, app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context.rb
Currently if a pod has no metrics data (for benign or malignant reasons) we:
a. raise an error and log a trace-log.
b. show users in the UI that metrics collection failed.
We want:
a. do not log missing data as an error ( usually this is benign behaviour of a pod not running )
b. do not show users an error message in the UI sammary page.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1530627
=> Do not raise an error when metrics are missing for one object

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture.rb, app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context.rb, app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context.rb
In #227 I forgot to re-catch the `NoMetricsFoundError` and prevent it from escalating to `CollectionFailure`.
Fix for PR https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/227
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1530627
=> recatch the metrics not found error

app/models/manageiq/providers/kubernetes/monitoring_manager_mixin.rb, spec/models/manageiq/providers/kubernetes/monitoring_manager_spec.rb
Other endpoints support both "verify_ssl" boolean and a
"security_protocol" string (which can be "ssl-without-validation",
"ssl-with-validation-custom-ca" or "ssl-with-validation".
While supporting both the boolean and the string is confusing,
it is important to be consistent across all endpoint types -
otherwise things can get very confusing for API users.
This commit makes sure the alerts endpoint calls verify_ssl_mode
just like other endpoints.
cc @moolitayer @cben
=> Properly support "security_protocol" for alerts endpoint

spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager/targeted_refresh/targeted_refresh_spec.rb
We hope to only use the fastest {:saver_strategy => :batch, :use_ar_object => false} in production, but testing all helps expose bugs in refresh...
=> Test :batch strategy with and without :use_ar_object.

app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
This will prevent issues and report correctly on event where the pod can't be accessed for some reason on that stage. This could happen for example if the pod is deleted by an external command.
=> abort container ssa if can't fetch metadata

manageiq-providers-kubernetes.gemspec
https://bugzilla.redhat.com/show_bug.cgi?id=1507528
@miq-bot add-label bug, gaprindashvili/yes
(On master, we'll later upgrade to kubeclient 3.0.0, need to resolve a version conflict first. On gaprindashvili, we'll stay with 2.5.)
@zeari @jhernand please review.
=> Bump kubeclient to >=2.5.2 <2.6

app/models/manageiq/providers/kubernetes/virtualization_manager_mixin.rb
When adding kubevirt provider with container provider at the same
request, there is no 'default' endpoint if the kubevirt provider is
added first. Therefore no need to check for hostname validation at that
point of time.
=> Skip hostname validation for virtualization manager

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb, config/settings.yml, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager/targeted_refresh/targeted_refresh_spec.rb
Symbols in configuration values are problematic because Symbols do not
roundtrip through JSON.  Since the API now exposes Settings, it's not
possible to set Symbols as values.  The saver_strategy was fixed in
https://github.com/ManageIQ/manageiq/pull/17168 to support String
values, and the next step is to remove all Symbols from the Settings.
https://github.com/ManageIQ/manageiq/issues/17201
https://bugzilla.redhat.com/show_bug.cgi?id=1558031
=> Change saver_strategy value to String

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
Currently when a user creates a scanning job we require `User.current_user` to be some value other than nil. But, when scheduling a scan for some period of time and then logging out / session times out `User.current_user` turns `nil` which causes the scanning job to break.
~~This patch fixes the above behavior to fallback to default user `system`.~~
Now we propagate `userid` through MiqSchedule which solves this issue.
Depends on: https://github.com/ManageIQ/manageiq/pull/17264
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1559459
cc: @cben @zeari
=> Propagate userid through to create a scanning job with current userid

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture.rb, config/settings.yml, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture_spec.rb
Add a config option to force legacy hawkular collector
This PR adds an option to force using old endpoint for metrics capture from Hawkular.
evm => configuration => advanced
**Screenshot** 
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1562090
=> Add a config option to force legacy hawkular collector

config/settings.yml, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture_spec.rb
As discussed in BZ's 1580816 and 1572022 we want to default to legacy Hawkular metrics collector.
Users that are sure they have compatible Hawkular install will still be able to use the new collector by setting the config parameter to false.
**Screenshot**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1580816
=> Default to force Hawkular legacy metrics collector

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
When changing the kubevirt's token under the virtualization tab, the new
token should be used for the validation check instead of the existing token.
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/77
Depends on https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/81
=> Respect kubevirt token if provided

spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
There are category/entry Tags, and category/entry Classifications.
```
.parent
category Classification "cat"   <----------   entry Classification "ent"
|^                ^                        |^
.tag||.classification  \_______________    .tag||.classification
v|                     .category   \       v|
category Tag /managed/cat                     entry Tag /managed/cat/ent
```
`.category` is supposed to get the "uncle", the category Classification from an *entry* Tag.
`mapping.tag` is a category Tag (for any-value mappings which are the kind we use).
Currently `.category` on a category Tag ("/managed/cat") happens to work same as `.classification`, but it's ill-defined and will stop working after https://github.com/ManageIQ/manageiq/pull/17418.
=> mapping.tag is a category Tag, calling .category is ill-defined

app/models/manageiq/providers/kubernetes/virtualization_manager_mixin.rb
The UI expects each provider to report its status.
Since kubevirt uses its own token, it might be valid while the container
provider is invalid.
That causes the default_auth_status in the UI [1] to report a failed
status when editing the kubevirt provider as an infrastructure provider,
since it refers to the status of the parent container manager. As a
result of that failure, the dialog cannot be saved.
For that purpose, the delegated call to authentication_status_ok? should
be implemented on the kubevirt provider side.
[1] https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/mixins/ems_common_angular.rb#L861
Provider's PR is here:
https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/92
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/71
=> Kubevirt should report its own status

app/models/manageiq/providers/kubernetes/virtualization_manager_mixin.rb
In addition to aca446f6561f34179519688a7540e93d85d25096 [1], another
authentication related method can be directed to kubevirt instead being
delegated to its parent provider.
[1] https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/259
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/35
=> Kubevirt should reports its auth status

app/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin.rb, app/models/manageiq/providers/kubernetes/container_manager/event_parser_mixin.rb, spec/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1583832
@miq-bot add-label bug, events, gaprindashvili/yes
EmsEvent.create_event drops "duplicate" events, determined by (event_type, timestamp, chain_id, ems_id, ems_ref).
Container events had no ems_ref (and no chain_id), meaning events of same type in same second collided and only one EmsEvent was created.
The lost events weren't handled by Automate / Policy.
Using k8s event's uid, not involvedObject's uid which still wouldn't be unique (for repeating events on same object).
4 EmsEvents created, with same timestamp and different ems_ref and.
@elad661 @moolitayer please review
=> Set EmsEvent ems_ref to event's uid, to avoid same-second collision

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/capture_context_mixin.rb
@miq-bot add-label technical debt
A step towards https://github.com/ManageIQ/manageiq-providers-kubernetes/issues/196.
`ems_id` is always set since we switched to soft delete.  `ems_id` got backfilled from `old_ems_id` for old disconnected records too by https://github.com/ManageIQ/manageiq-schema/pull/18.
@zeari @Ladas please review
=> Stop falling back to old_ems_id

app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb, app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, app/models/manageiq/providers/kubernetes/inventory/persister.rb, app/models/manageiq/providers/kubernetes/inventory/persister/container_manager.rb, app/models/manageiq/providers/kubernetes/inventory/persister/definitions/container_collections.rb, app/models/manageiq/providers/kubernetes/inventory/persister/target_collection.rb
**Issue**: https://github.com/ManageIQ/manageiq/issues/17396
- **dependent**: https://github.com/ManageIQ/manageiq-providers-openshift/pull/100
New Interface for definition/creating InventoryCollection from persister.
Using add_collection() instead of add_inventory_collection() to build collections.
Builder classes are defined on core project, provider specific InventoryCollections specified in concerns
=> Persister: InventoryCollection building through add_collection()

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
Move the method which checks if streaming_refresh is enabled in config
closer to the supports :streaming_refresh block.
Ref: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/271#discussion_r211266196
=> Move streaming_refresh_enabled method

app/models/manageiq/providers/kubernetes/container_manager/streaming_refresh_mixin.rb
If a watch thread fails for any reason (exception, timeout, etc...)
restart it with the last resourceVersion so it picks up where it left
off.
=> Restart stale watch threads where they left off

app/models/manageiq/providers/kubernetes/container_manager/streaming_refresh_mixin.rb
Prevent thread joins always timing out due to the watch stream blocking
for far longer than the join timeout.
Ref: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/271#discussion_r212213786
=> Finish the watch stream connection when exiting

app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb
Running against minishift I get a KubeException 404 error collecting
service catalog classes and plans:
An error has occurred during work processing: HTTP status code 404, 404
Not Found
=> Handle missing service catalog endpoint

app/models/manageiq/providers/kubernetes/inventory/collector/watches.rb
Using watches with the service catalog endpoint is failing when it goes to parse a watch update.  Eventually we should use watches for the services but not up to that yet
=> Fix watches when using service catalog endpoint

app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb, app/models/manageiq/providers/kubernetes/inventory/collector/watches.rb
Rather than waiting to call Kubeclient::Client#get_entity_type for
the 404 exception we can call Kubeclient::Client#discover and catch the
exception when connecting.
=> Use discover to catch service catalog

spec/factories/ext_management_system.rb, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_client_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_legacy_capture_context_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/rollup_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager/targeted_refresh/targeted_refresh_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
Specs for metrics capture were failing due to a missing zone on the EMS
=> Fix MetricsCapture and Refresher specs failing due to a missing zone

app/models/manageiq/providers/kubernetes/container_manager/streaming_refresh_mixin.rb, app/models/manageiq/providers/kubernetes/container_manager_mixin.rb, app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb, app/models/manageiq/providers/kubernetes/inventory/collector/watches.rb, app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb
This adds the service_catalog entity types to the list of watched entities.
1. I had to change the collector methods from cluster_service_offerings and cluster_service_parameters_sets to the native entity type so that i could get the resourceVersion with the entity type from the collection.
2. I moved from using `ems.connect` to saving the connect options and using raw_connect so that each thread didn't require an ActiveRecord connection.  With 5 threads I was exhausting the number of connections in the connection pool.
Dependent: https://github.com/ManageIQ/manageiq-providers-openshift/pull/113
=> Streaming refresh for service catalog entities

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb, app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb, spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
Call discover when connecting to a kubernetes endpoint to prevent exceptions on future method calls.
=> Discover API endpoint in kubernetes_connection

.travis.yml
9.4 support dropped in https://github.com/ManageIQ/manageiq/pull/18090.
Should fix bin/setup failure (and possibly later problems): https://travis-ci.org/ManageIQ/manageiq-providers-kubernetes/jobs/442105217#L1939-L1980.
Matches core change https://github.com/ManageIQ/manageiq/pull/15994.
=> Travis - change postgresql to 9.5

spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/rollup_spec.rb
https://github.com/ManageIQ/manageiq/pull/18159 Fixed project rollups for aggregate memory and CPU so we need to fix rollup specs
Fixes https://github.com/ManageIQ/manageiq-providers-kubernetes/issues/301
=> Fix rollup specs for project derived mem/cpu

app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
State finishing does not exist in hammer branch.
Followup of https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/303.
https://bugzilla.redhat.com/show_bug.cgi?id=1499161
@miq-bot add_label bug, hammer/yes
cc @gmcculloug
=> Different way to check for scan job's complete state.

app/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin.rb, spec/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin_spec.rb
The base_manager event_catcher maintains a list of filtered events from the ems event type blacklist. This list should be checked when checking if an event is to be filtered or not.
\+ Combine all of the filtered logic into the filtered? method and extract it from extract_event_data.
Based on ManageIQ/manageiq#14632
~~Depends on: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/308~~
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1653871
=> Refactor the event catcher filtered? method

spec/models/manageiq/providers/kubernetes/monitoring_manager_spec.rb
https://github.com/ManageIQ/manageiq/pull/18266 changed factories by default to create "Valid" auth, requiring explicit opt-out for test scenarios like here unvalidated->`check_types`->expected status.
Fixes red travis: https://travis-ci.org/ManageIQ/manageiq-providers-kubernetes/jobs/474807718#L2098
(tracking issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/4921#issuecomment-451129620)
@kbrock @bdunne please review
=> MonitoringManager spec: update to explicitly start from unvalidated auth

app/models/manageiq/providers/kubernetes/inventory/persister/container_manager.rb
The shared_options were duplicated from the base persister
=> Remove duplicated persister shared_options

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
Instead of calling Job.create_job and passing the scanning job class
name we can call create_job from the final class not the base class.
This opens up future refactorings for the base create_job class.
=> Call .create_job from the Scanning class

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture.rb, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/rollup_spec.rb
update_attributes and update_attributes! are deprecated starting in Rails 6
See https://rubyinrails.com/2019/04/09/rails-6-1-activerecord-deprecates-update-attributes-methods/ for details and Rails PR links.
=> update_attributes deprecation

app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1751267
Setting "hostname" was an enhancement in https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/248 to improve image names but it introduced a regression:
Pod spec could be invalid for long image names, causing scanning to not run at all.
(Possibly also for weird characters in name, not sure if realistic but made code more robust to that too.)
----
Expanded comments to clarify lowercase requirement is by Kubernetes not the DNS RFC (https://github.com/kubernetes/kubernetes/pull/39675).
The RFC also says:
> Host software MUST handle host names of up to 63 characters and SHOULD handle host names of up to 255 characters
so a bit ambiguous what's "valid DNS label" means but anyway Kubernetes enforces 63 (some history on …
=> Fix scanning pod fake "hostname" for long image names

app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb
If the storage capacity attribute is of the form 50M or 1G the
parse_capacity_field method which only expects IEC 60027-2 style values
will fail:
```
MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshParser#parse_capacity_field) Capacity attribute - storage was in bad format - 1G
```
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1782902
=> Fix parsing capacity fields of the form 50M or 1G

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture.rb, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture_spec.rb
kubernetes is a container metrics capture class. subclassing the proper parent
part of ManageIQ/manageiq#19684
=> Subclass ContainerManager metrics capture

app/models/manageiq/providers/kubernetes/container_manager/container_template_mixin.rb, app/models/manageiq/providers/kubernetes/container_manager/refresher_mixin.rb, app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb, app/models/manageiq/providers/kubernetes/container_manager/streaming_refresh_mixin.rb, app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresh_mixin_spec.rb
Note, there doesn't seem to be one single entrypoint for these classes and
mixins so when possible, we now autoload any constants being used in these
files.
Note, it's best to require or use ruby's autoload on libraries like this.
Normal rails models and other files that need to be reloaded by rails in dev
mode need to be loaded by using the constant directly to force const_missing
or use require_dependency.
=> Lazy load kubeclient/image inspector library with autoload

spec/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin_spec.rb, spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
Refactoring PR that eliminates a constant redefinition warning. It also implements previously undefined methods either by including the `Vmdb::Logging` module (for the `_log` method) or by defining it directly (the `log_prefix` method). Without these, the specs fail with strict partial validation turned on.
There are other constants that should probably be replaced with `let` but this PR just focuses on fixes for now.
=> Fix warning and strict partial failure

app/models/manageiq/providers/kubernetes/container_manager/refresher_mixin.rb, app/models/manageiq/providers/kubernetes/inventory/persister/definitions/container_collections.rb
Instead of an extra method in the Refresher class we can raise creation
events with an inventory_collection which is more consistent with how
this is typically done and we can clean up the base Refresher class.
Containers were the only providers that actually used this
manager_refresh_post_processing method and it can be deleted now.
Depends on: ~~https://github.com/ManageIQ/manageiq/pull/19973~~
=> Use an inventory_collection to raise created events

spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/rollup_spec.rb
Depending on the floating point precision the rollup spec would
sometimes fail to match:
```
1) ManageIQ::Providers::Kubernetes::ContainerManager::Refresher check project rollup can handle partial hour
Failure/Error:
expect(project_rollup).to(
have_attributes(
:derived_memory_used        => 2048.0,
:derived_vm_numvcpus        => 12.0,
:derived_memory_available   => 3072.0,
:mem_usage_absolute_average => 66.6666666666667
)
)
expected #<MetricRollup id: 25000000000170, timestamp: "2012-09-01 00:00:00", capture_interval: nil, resource_...up_create_rate: 0, stat_container_group_delete_rate: 0, stat_container_image_registration_rate: nil> to have attributes {:derived_memory_available => 3072.0, :derived_memory_used => 2048.0, :derived_vm_numvcpus => 12.0, :mem_usage_absolute_average => …
```
=> Use be_within to fix rollup_spec sporadic failure

manageiq-providers-kubernetes.gemspec
Kubeclient is up to 4.6 and we were back on 4.1.  We can't update past 4.3 yet because of kubevirt but this gets us closer
=> Bump kubeclient to newer version

app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb, spec/models/manageiq/providers/kubernetes/inventory/parser/container_manager_spec.rb
The ContainerManager Parser was written to allow for the core parsing to
be shared with graph and legacy refresh which is why a number of items
are added to the hash then deleted and handled differently.
This can all be cleaned up now that we only use graph refresh.
=> Refactor Parser::ContainerManager

spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
The main body of refresh specs were shared between classic and graph
refresh contexts.
Now that there is no classic refresh being tested we no longer need the
shared context.
=> Move no-longer-shared specs into main context

app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/runner.rb, app/models/manageiq/providers/kubernetes/inventory/collector.rb, app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb, app/models/manageiq/providers/kubernetes/inventory/collector/watch_notice.rb, app/models/manageiq/providers/kubernetes/inventory/parser/watch_notice.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb, spec/models/manageiq/providers/kubernetes/inventory/collector/watch_notice_spec.rb
Services and endpoints are different k8s collections but are combined into one model in the MIQ refresh parser.  This means we cannot parse these as standalone notices like the other collections.
If we get a notice about either an endpoint or a service, perform a get_ for the other to allow the parser to work normally.
Followup to https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/366
=> Add targeted refresh for services and endpoints

app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb, app/models/manageiq/providers/kubernetes/inventory/parser/watch_notice.rb, app/models/manageiq/providers/kubernetes/inventory/persister.rb
Not all entity types use metadata.uid as the manager ref (e.g. OpenShift BuildPods use [name, namespace]).
Needed for: https://github.com/ManageIQ/manageiq-providers-openshift/pull/169
=> Add parser methods for entity manager_refs

manageiq-providers-kubernetes.gemspec
Bump kubeclient to version 4.6.  Besides just staying up-to-date this ensures that we can use k8s watches with ruby 2.7 (see https://github.com/abonas/kubeclient/issues/442)
https://github.com/ManageIQ/manageiq/issues/19678
=> Update kubeclient to v4.6

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
Some recent refactoring caused the ContainerManager#queue_metrics_capture call to start failing.
=> We moved capture_container_targets out of Metric::Target

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context.rb, spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_node_metrics.yml, spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_node_timespan.yml, spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_pod_metrics.yml, spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_pod_timespan.yml
If the container node network interfaces are named e.g. ens0 instead of eth0 the query for network metrics fails causing no node metrics to be saved.
According to the Linux Consistent Network Device Naming conventions [ref](https://en.wikipedia.org/wiki/Consistent_Network_Device_Naming) ifaces can be `eth[0..N]`, `eno[1..N]`, `ens[1..N]`, or `enp<PCI Slot>s<Card Number>`.
Example prometheus query with the newer interface naming:
=> Fix node network metrics with ens.* interfaces

manageiq-providers-kubernetes.gemspec
more core ext's on 4.1.0
update for update sake
https://github.com/ManageIQ/more_core_extensions/compare/179bf40..e5b4501
- Added Ruby 2.7 support [[#79](https://github.com/ManageIQ/more_core_extensions/pull/79)]
- Added Process#pause, Process#resume, and Process#alive? [[#73](https://github.com/ManageIQ/more_core_extensions/pull/73)]
array added * `#compact_map` - Collect non-nil results from the block
array added `#tabular_sort` - Sorts an Array of Hashes by specific columns
hierarchy added `#descendant_get` - Returns the descendant with a given name
the two breaking changes:
- **BREAKING**: Moved Object#descendant_get to Class#descendant_get [[#75](https://github.com/ManageIQ/more_core_extensions/pull/75)]
- **BREAKING**: Removed deprecated Enumerable#stable_sort_by …
=> bump more core extension dependency

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
The only callers then call `#to_miq_a`
https://github.com/ManageIQ/manageiq/blob/33d994ae207105a508d9e214d39d9ec66ac066dd/app/models/metric/rollup.rb#L189
https://github.com/ManageIQ/manageiq/blob/33d994ae207105a508d9e214d39d9ec66ac066dd/app/models/metric/rollup.rb#L204
=> PERF_ROLLUP_CHILDREN should be an Array

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb, app/models/manageiq/providers/kubernetes/monitoring_manager_mixin.rb
In order to make this form work, I had to do some tradeoffs:
* The `default_value_for` in the `ContainerManagerMixin` prevents the usage of `create_from_params` so I deleted it.
* We are (kinda) using the same authentication for each endpoint (except kubevirt) by copying the same authentication with different authtypes. I solved this via redefining the `.create_from_params` with the replication of the same data among endpoints. However, I'd rather see the provider using just the single authentication instead.
* As we never send down passwords to the client and the token authentication has no any public value that we could send down, we end up with not submitting anything in the `authentications` if there's no token change. This can cause all authentications to be deleted upon an edit …
=> Adjusted DDF schema and credentials validation

app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb
When a watch fails the status and code are in the notice.object not the top level resource.
Thanks to @jrafanie for testing this:
```
irb(main):047:0> watches = co.send(:kube_connection).watch_pods(:namespace => "gt-lj-manageiq-slow-fyre", :resource_version => 199900).to_enum
=> #<Enumerator: #<Kubeclient::Common::WatchStream:0x0000560cd2222718 @uri=#<URI::HTTPS https://172.30.0.1/api/v1/watch/namespaces/gt-lj-manageiq-slow-fyre/pods?resourceVersion=199900>, @http_client=nil, @http_options={:basic_auth_user=>nil, :basic_auth_password=>nil, :headers=>{:Authorization=>"Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJndC1sai1tYW5hZ2VpcS1zbG93LWZ5cmUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC …
```
=> Fix handling of watch notice errors from k8s

manageiq-providers-kubernetes.gemspec
This allows us to use newer versions of faraday (https://github.com/openshift/prometheus-alert-buffer-client-ruby/commit/2cfffa028df814e8f8ca8175aa7b07ce4817961a)
=> Bump the Prometheus Alert Buffer Client gem

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
The default behavior for the `async-credentials` component is [changing to be optional](https://github.com/ManageIQ/manageiq-ui-classic/pull/7347), so it has to be explicitly marked as required here. This is a little different from any other provider, not just the default credentials are required as all the other components are only rendered when the user selects the right protocol from the dropdown.
=> Make the credentials required in the provider DDF

app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb
Starting the watch threads assigns the watch thread to a self.thread instance variable, this is throwing a private method exception on older rubies (I don't see this on 2.7)
```
ERROR -- : [NoMethodError]: private method 'watch' called for #<ManageIQ::Providers::Openshift::ContainerManager::RefreshWorker::WatchThread:0x0000558b852f8af8>
ERROR -- : app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb:43:in 'collector_thread'
app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb:23:in 'block in start!'
```
This isn't the default on jansa so it isn't critical to be backported, but a user could change the settings and enable it.
=> Fix "private method 'watch' called for WatchThread"

spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
~~Allow auto_model_class to set the type automatically~~ Until Openshift subclasses these models we can't use auto_model_class yet
Tests for: https://github.com/ManageIQ/manageiq/pull/20801
=> Test the STI types are set properly by Refresh

app/models/manageiq/providers/kubernetes/container_manager_mixin.rb, app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb, spec/models/manageiq/providers/kubernetes/inventory/parser/container_manager_spec.rb
The rubocop linter picked up a couple things. Specifically, there's no need to do safe navigation on a `kind_of?` check since `NilClass` implements it.
I also marked the `pod_id` variable in `parse_container_status` as unused. I can remove it, but wasn't sure if the second argument was there to comply with an interface.
=> Mark unused variable, remove redundant safe navigation

app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb
Last of the linter warnings for now, this just removes a variable that was never used.
=> Remove unused port variable

app/models/manageiq/providers/kubernetes/container_manager.rb
The connect options for the class-level take `options[:username]` and `options[:password]` but the instance connect passes `options[:user]` and `options[:pass]`
These [`connect_options`](https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/fc33713d32bcaa3a0b345aaa5f19dab1865c929a/app/models/manageiq/providers/kubernetes/container_manager.rb#L998-L1011) are passed directly to [`.raw_connect`](https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/fc33713d32bcaa3a0b345aaa5f19dab1865c929a/app/models/manageiq/providers/kubernetes/container_manager.rb#L995) which is just [`kubernetes_connect`](https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/fc33713d32bcaa3a0b345aaa5f19dab1865c929a/app/models/manageiq/providers/kubernetes/container_manager.rb#L58-L60) and none …
=> Fix instance connect options for username/password

app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/runner.rb, app/models/manageiq/providers/kubernetes/inventory/collector.rb, app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb, app/models/manageiq/providers/kubernetes/inventory/collector/container_manager/watch_notice.rb, app/models/manageiq/providers/kubernetes/inventory/parser.rb, app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb, app/models/manageiq/providers/kubernetes/inventory/parser/container_manager/watch_notice.rb, app/models/manageiq/providers/kubernetes/inventory/persister.rb, app/models/manageiq/providers/kubernetes/inventory/persister/container_manager.rb, app/models/manageiq/providers/kubernetes/inventory/persister/container_manager/watch_notice.rb, app/models/manageiq/providers/kubernetes/inventory/persister/watch_notice.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb, spec/models/manageiq/providers/kubernetes/inventory/collector/container_manager/watch_notice_spec.rb
If we include a `ContainerManager` in a vendor with e.g. a `CloudManager` then the `WatchNotice` is confusingly not visually a part of the `ContainerManager`.
E.g.:
```
amazon/inventory/collector/cloud_manager
amazon/inventory/collector/container_manager
amazon/inventory/collector/watch_notice # Not obvious that this is a container_manager collector
```
Co-depends:
https://github.com/ManageIQ/manageiq-providers-openshift/pull/204
=> Move Inventory WatchNotice under ContainerManager

app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb
Add a filter_notices method that can be subclassed by other providers and skip the refresh if there are no filtered notices left.
=> Skip refresh if no notices left after filtering

app/models/manageiq/providers/kubernetes/container_manager.rb
Because carbon has four different dropdowns, the DDF schemas need to have explicit initialValue or includeEmpty settings in order to make the form validation work.
@miq-bot assign @agrare
=> Adjust empty/initial values for select fields in DDF schemas

app/models/manageiq/providers/kubernetes/container_manager.rb
from https://github.com/hawkular/hawkular-client-ruby:
```
You can also access each subproject's API individually, if you would like to use only the metrics API you could do
require 'hawkular/metrics/metrics_client'
metrics_client = Hawkular::Metrics::Client.new(
entrypoint: 'http://localhost:8080/hawkular/metrics',
credentials: { username: 'jdoe', password: 'password' },
options: { tenant: 'hawkular' }
)
```
@miq-bot assign @agrare
=> Require hawkular metrics clients in container manager

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture.rb, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture_spec.rb
If the authentication for the metrics credentials is invalid we can end up spewing lots of huge log messages with the exception that is returned for each metrics target (can be thousands a minute).
```
[----] I, [2021-03-26T14:24:42.161946 #743495:145a0]  INFO -- : MIQ(ManageIQ::Providers::Openshift::ContainerManager::ContainerNode#just_perf_capture) [realtime] Capture for ManageIQ::Providers::Openshift::ContainerManager::ContainerNode name: [openshift.example.com], id: [1], start_time: [2021-03-26 00:00:00 UTC]...
[----] I, [2021-03-26T14:24:45.833725 #743495:145a0]  INFO -- : MIQ(ManageIQ::Providers::Kubernetes::ContainerManager::MetricsCapture#perf_collect_metrics) Collecting metrics for ContainerNode(1) [realtime] [2021-03-26 00:00:00 UTC] []
[----] W, [2021-03-26T14:24:45.973769 …
```
=> Only collect metrics if the metrics endpoint has valid authentication

app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb, spec/models/manageiq/providers/kubernetes/inventory/parser/container_manager_spec.rb
If the Node systemUUID contains a null byte the PostgreSQL query throws an exception
=> Handle a null byte in Node systemUUID

app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb, spec/models/manageiq/providers/kubernetes/inventory/parser/container_manager_spec.rb
When K8s is installed on power it has been seen that the nodes' systemUUID property contains null bytes.  This was causing the cross_link_node query to fail but once we get past that the save_inventory also fails.
Strip null bytes before saving the node hash to fix:
```
[----] I, [2021-05-20T15:17:49.836289 #456047:2ab88a5f7964]  INFO -- : EMS: [OCPpower], id: [16] Saving EMS Inventory...
[----] E, [2021-05-20T15:17:49.893094 #456047:2ab88a5f7964] ERROR -- : Error when saving InventoryCollection:<ContainerNode> with strategy: , saver_strategy: batch, targeted: false. Message: string contains null byte
[----] E, [2021-05-20T15:17:49.893391 #456047:2ab88a5f7964] ERROR -- : MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshWorker::Runner#refresh_block) EMS [OCPpower], id: [16] …
```
=> Strip any null bytes from systemUUID in node hash

app/models/manageiq/providers/kubernetes/container_manager.rb, spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
If the credentials or hostname change we should restart the refresh worker to break the blocking open connections that use the old credentials/endpoint
Fixes https://github.com/ManageIQ/manageiq/issues/21253
=> Restart the refresh worker when credentials change

app/models/manageiq/providers/kubernetes/container_manager.rb, spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
Override the base `hostname_uniqueness_valid?` method for container managers to allow for multiple EMSs with the same hostname but different ports.
=> Allow duplicate hostnames with different ports

app/models/manageiq/providers/kubernetes/container_manager.rb
When calling `supports :metrics`, the SupportsFeatureMixin defines a `supports_metrics?` method via its
`define_supports_feature_methods` method [here](https://github.com/ManageIQ/manageiq/blob/master/app/models/mixins/supports_feature_mixin.rb#L145)
=> Rename supports_metrics? method to metrics_endpoint_exists?

spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
(cherry picked from commit 2588e87b6fe291e1c50a72b3ff5ae25b28c62365)
Cherry-pick of https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/437/commits/2588e87b6fe291e1c50a72b3ff5ae25b28c62365 from https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/437
Fixes https://app.travis-ci.com/github/ManageIQ/manageiq-providers-kubernetes/builds/245733067
=> [MORPHY] Fix destroy queue item expectation

app/models/manageiq/providers/kubernetes/container_manager/metrics_collector_worker.rb, spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
We're migrating away from `supports_metrics?` to `supports?(:metrics)`
=> transition to supports(:metrics)

app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb
The lazy_find_by method is no different from the lazy_find method now and will be removed in an upcoming inventory_refresh release
=> Replace lazy_find_by with simple lazy_find

manageiq-providers-kubernetes.gemspec
* kubeclient 4.7.0 added ruby 3 support in https://github.com/ManageIQ/kubeclient/pull 438
* Loosen recursive-open-struct requirement to allow kubeclient 4.7.0+.
=> Update dependencies for ruby 3 support

app/models/manageiq/providers/kubernetes/container_manager.rb
The EmsRefreshMixin checks for allow_targeted_refresh before queueing a target and it isn't supported it will queue a full.
This will cause the streaming refresher to shutdown all watch threads and do a full refresh again.
Ref: https://github.com/ManageIQ/manageiq-providers-vmware/pull/833
=> Add allow_targeted_refresh to prevent fulls

app/models/manageiq/providers/kubernetes/container_manager/metrics_collector_worker.rb
The method do check for all valid EMSs in the zone has changed.
This was introduced by https://github.com/ManageIQ/manageiq/pull/21060 I didn't realize there were direct callers of [`emses_in_zone`](https://github.com/ManageIQ/manageiq/pull/21060/files#diff-e1cf43c568a786d79f0b65433e154483cc7a3abbdfbf6471cc54e2916ca94ea1L15-L17) I thought it was only used by [`any_valid_ems_in_zone?`](https://github.com/ManageIQ/manageiq/pull/21060/files#diff-e1cf43c568a786d79f0b65433e154483cc7a3abbdfbf6471cc54e2916ca94ea1L19-L21) which was changed to use the more standard `all_ems_in_zone` method
Follow-ups:
* Fix Openshift MetricsCollectorWorker
* Fix IBM Cloud IKS MetricsCollectorWorker
=> Fix the MetricsCollectorWorker running with invalid creds

app/models/manageiq/providers/kubernetes/container_manager.rb, spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
When editing a provider the auth_key isn't sent back down unless the auth was changed.  This led to a case where adding a metrics endpoint while editing a provider would create an authentication record without an auth_key resulting in a "Missing Credentials" on the subsequent validation.
Fixes https://github.com/ManageIQ/manageiq-providers-openshift/issues/237
=> Fix blank metrics auth record being created

lib/manageiq-providers-kubernetes.rb, lib/manageiq/providers/kubernetes.rb, spec/spec_helper.rb
Adopt convention already supported by bundler and required by zeitwerk so we don't need to tell zeitwerk to ignore this lib/gem-name.rb file.
=> Drop lib/gem-name.rb in favor of lib/gem/name.rb

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context.rb, spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_node_metrics.yml, spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_node_timespan.yml, spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_pod_metrics.yml, spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_pod_timespan.yml
Container Nodes on the s390x architecture have interfaces called `enc.*` which was causing no net_usage_rate_average values to be returned.
NOTE originally I reported that `br0` worked, and while it does x86 nodes also have a `br0` and we specifically request the underlying interfaces rather than the bridge.  For a fix for backport I wanted to maintain this behavior while investigating if there is a more reliable way of getting the metrics we're looking for.
=> Fix Node network metrics collection on s390x

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/capture_context_mixin.rb, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_spec.rb
Only filter out timestamps which have partial metric values for counters which exist in other timestamps.  If no timestamp has a counter then we should consider it requested but not returned and continue on.
https://github.com/ManageIQ/manageiq-providers-kubernetes/issues/485
=> Don't exclude all metrics if one counter is missing

app/models/manageiq/providers/kubernetes/container_manager.rb
```
[----] I, [2023-05-10T12:24:21.333269 #198911:9650]  INFO -- evm: MIQ(MiqTask#update_status) Task: [76] [Active] [Ok] [Task starting]
[----] E, [2023-05-10T12:24:21.443082 #198911:9650] ERROR -- evm: MIQ(MiqQueue#deliver) Message id: [341241], Error: [undefined local variable or method `parent' for ManageIQ::Providers::Openshift::ContainerManager:Class
Did you mean?  print]
[----] E, [2023-05-10T12:24:21.443267 #198911:9650] ERROR -- evm: [NameError]: undefined local variable or method `parent' for ManageIQ::Providers::Openshift::ContainerManager:Class
Did you mean?  print  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2023-05-10T12:24:21.443396 #198911:9650] ERROR -- evm: /home/grare/adam/.gem/ruby/3.0.0/gems/activerecord-6.1.7.3/lib/active_record/dynamic_matchers.rb:22:in …
```
=> Fix method missing `:parent` should be module_parent

app/models/manageiq/providers/kubernetes/container_manager.rb
Fix undefined RestClient exceptions when verifying prometheus-alerts credentials.
Because the prometheus-alerts gem does not use rest-client unless you verify "default" credentials rest-client is not going to be required.
Depends on:
=> Fix undefined rest client exceptions

app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/runner.rb, app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread_spec.rb
Instead of trying to restart a watch when a 410 Gone error is received just let the thread die and be restarted.
=> Restart collector threads on 410 Gone

app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread_spec.rb
Don't restart a watch without finishing the previous one
=> Ensure WatchStream is always finished

app/models/manageiq/providers/kubernetes/container_manager.rb
Right now, when editing the default endpoint token of a provider like Openshift, the provider form forces the user to revalidate the Metrics and Alerts endpoints as well however, this isn't apparent to the user unless they switch to that tab and check which can lead to confusion when trying to save.
Before:
After:
**Note:** This is a temporary fix. The goal is to later undo this change and introduce a way for the ui to alert the user that they have to revalidate the other endpoints before saving their edits.
=> Removed the `auth_key` from list of Validation Dependencies in Metrics and Alerts

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture.rb, spec/factories/container_group.rb, spec/factories/ext_management_system.rb, spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture_spec.rb
Check that the EMS's metrics authentication is valid before queueing perf_capture calls, potentially flooding the queue with calls that are going to fail later.
=> Check metrics authentication validity before perf_capture_queue

app/models/manageiq/providers/kubernetes/container_manager.rb
This reverts commit 7be0a737edac7c0af5b43fdef6bfac1627826a33, reversing changes made to 6acc47038cebd128bb542d0b4ce85c65f53315c8.
This commit caused a bigger issue in that metric validation fails entirely.
=> Revert "Merge pull request #492 from DavidResende0/remove-validation-dependecies"

app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb
Thread#join used to accept duration objects but not since ruby 3/rails 6.1
See also https://github.com/ManageIQ/manageiq-providers-vmware/pull/832
=> Convert the duration to a float

app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
The `state_info` had symbol keys like `:startedAt` and `:finishedAt` and we were looking for string keys like `"startedAt"` and `"finishedAt"` causing these values to always be `nil` even if data existed in the API response.
=> Fix started_at/finished_at always being nil

app/models/manageiq/providers/kubernetes/inventory/collector.rb
If a token is invalid when a refresh starts the connect method was eating the exception and returning `nil` rather than allowing the refresh to fail.
=> Fix No Method get_nodes for NilClass invalid token

app/models/manageiq/providers/kubernetes/container_manager.rb
Adds some text to the Token Field notifying the user that the Default, Metrics, and Alerts endpoints must be revalidated anytime the Token is updated if that endpoint is enabled.
Before:
After:
The long term goal is to add a clearer visual cue that illustrates this fact to the user.
=> Added Helper Text To the Token Field

app/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin.rb, spec/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin_spec.rb
The event timestamp is critical for uniquely identifying events and ensuring there are no duplicates.
We cannot properly handle events without a timestamp so we need to not queue these for the event handler.
=> Reject any events which do not have a timestamp

spec/models/manageiq/providers/kubernetes/container_manager/scanning/job/dispatcher_spec.rb
Part of https://github.com/ManageIQ/manageiq/issues/22696
=> We explicitly serialize objects so we need to permit yaml loading them

app/models/manageiq/providers/kubernetes/container_manager.rb
part of:
- https://github.com/ManageIQ/manageiq/pull/22898
Deprecating `unsupported_reason_add`. Returning the string instead
Note, these are all the same:
```ruby
unsupported_reason_add(:feature, unsupported_reason(:feature2)) unless supports_feature2?
unsupported_reason_add(:feature, unsupported_reason(:feature2)) unless supports?(:feature2)
unsupported_reason(:feature2) unless supports?(:feature2)
unsupported_reason(:feature2)
```
=> drop unsupported_reason_add

app/models/manageiq/providers/kubernetes/container_manager.rb
Ensure that the Kubeclient::HttpError exception class is loaded in the connection_rescue_block method when verifying the prometheus endpoint.
```
[NameError]: uninitialized constant ManageIQ::Providers::Kubernetes::ContainerManager::Kubeclient
rescue RestClient::Unauthorized, Kubeclient::HttpError => err
ERROR -- evm: /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-7e766229622c/app/models/manageiq/providers/kubernetes/container_manager.rb:596:in `rescue in connection_rescue_block'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-7e766229622c/app/models/manageiq/providers/kubernetes/container_manager.rb:588:in `connection_rescue_block'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-7e766229622c/app/models/manageiq/pr …
```
=> Require kubeclient in connection_rescue_block

app/models/manageiq/providers/kubernetes/container_manager.rb, app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_mixin.rb
When `VMDB::Util.http_proxy_uri` is `nil` `VMDB::Util.http_proxy_uri.to_s` is `""`.
With uri v0.10.3 `URI.parse("http://")` would have a `host` of `nil` but on v0.13.0 `URI.parse("http://")` has a `host` of `""`.
This was causing Faraday to use a proxy of `0.0.0.0:80` instead of none.
`prometheus-api-client-0.6.2/lib/prometheus/api_client/client.rb:106:in 'rescue in run_command': Failed to open TCP connection to :80 (Connection refused - connect(2) for 0.0.0.0:80) (Prometheus::ApiClient::Client::RequestError)`
=> Fix prometheus http_proxy using 0.0.0.0:80

app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_mixin.rb
Most of the overhead is eager loading faraday but there's no need for domain models to load this client until it's needed by code needing this client.
=> Delay load prometheus client

spec/models/manageiq/providers/kubernetes/container_manager/scanning/job/dispatcher_spec.rb
This supports rails 7 and 6.1.
Similar to the change in: https://github.com/ManageIQ/manageiq/pull/22887
=> Provide backward compatible way to globally set permitted classes

app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb, app/models/manageiq/providers/kubernetes/inventory/persister/definitions/container_collections.rb, spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
Add parse_annotations method and add them to custom attributes of container summary pages that have labels
Relevant PRs:
UI-Classic: https://github.com/ManageIQ/manageiq-ui-classic/pull/9214
Providers-Openshift: https://github.com/ManageIQ/manageiq-providers-openshift/pull/262
Core ManageIQ: https://github.com/ManageIQ/manageiq/pull/23074
Cross-Repo Tests:
https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/879 
All passing except for known failing test cases in core ManageIQ
=> Add annotations to container summary pages

app/models/manageiq/providers/kubernetes/container_manager.rb
=> Clarify that KubeVirt is OSV

spec/models/manageiq/providers/kubernetes/container_manager/scanning/job/dispatcher_spec.rb
Drops the rails 6.1 compatibility from:
https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/531
=> Use Rails 7 way to set yaml permitted classes

app/models/manageiq/providers/kubernetes/container_manager.rb
See comment https://github.com/ManageIQ/manageiq-providers-openshift/pull/264#issuecomment-2274484947
Depends on:
@miq-bot assign @agrare 
@miq-bot add_label enhancement
@miq-bot add_reviewer @agrare
=> Separate OSV and Kubevirt virtualization options from form

app/models/manageiq/providers/kubernetes/container_manager.rb, app/models/manageiq/providers/kubernetes/container_manager/options.rb
Newlines can cause trouble with translations as well as presentation in the UI. This particular string doesn't actually need the newlines, so this commit changes it to just not have them.
Alternative to ManageIQ/manageiq#23213
@agrare Please review. cc @jrafanie
=> Remove newlines from help message

app/models/manageiq/providers/kubernetes/monitoring_manager.rb, app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/stream.rb
=> [QUINTEROS] JSON parse prometheus_alert client responses
